const CHANGE_BETWEEN_COL = 'CHANGE_COL_WITH_COL';
const CHANGE_IN_COL = 'CHANGE_IN_COL';
const ADD_TASK_COL = 'ADD_TASK_COL';
const DELETE_TASK_COL = 'DELETE_TASK_COL';
const LOAD_LOCAL_COL = 'LOAD_LOCAL_COL';
const LOAD_COL = 'LOAD_COL';

export {
	CHANGE_BETWEEN_COL,
	CHANGE_IN_COL,
	ADD_TASK_COL,
	DELETE_TASK_COL,
	LOAD_LOCAL_COL,
	LOAD_COL,
};
