const ADD_TASK = 'ADD_TASK';
const EDIT_TASK = 'EDIT_TASK';
const DELETE_TASK = 'DELETE_TASK';
const SET_TMP_TASK = 'SET_TMP_TASK';
const LOAD_LOCAL_TASK = 'LOAD_LOCAL_TASK';

export { ADD_TASK, EDIT_TASK, DELETE_TASK, SET_TMP_TASK, LOAD_LOCAL_TASK };
